---
app:
  is-debug: true
  log-level: warning
  admin:
    email: admin@taod.ru
    password: "123"
  jwt-secret: "some-amazing-shit"

http:
  ip: 0.0.0.0
  port: 10000
  cors:
    debug: true
    allowed-methods: ["GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE"]
    allowed-origins:
      - "http://localhost:3000"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options-passthrough: true
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"

postgresql:
  host: 0.0.0.0
  port: 5434
  username: admin
  password: admin
  database: go_world
  database-type: postgres